export { Detail } from './Detail'
export { Favs } from './Favs'
export { Home } from './Home'
export { RegisterUser } from './RegisterUser'
export { LoginUser } from './LoginUser'
export { User } from './User'
